"""Theme definitions for the application."""

THEMES = {
    # Minimal Light - Clean, airy, white-on-white
    "Minimal Light": {
        "bg": "#FAFAFA",
        "fg": "#333333",
        "header_bg": "#FAFAFA",
        "header_fg": "#111111",
        "button_bg": "#111111",
        "button_fg": "#FFFFFF",
        "tree_bg": "#FFFFFF",
        "tree_fg": "#333333",
        "tree_heading_bg": "#FAFAFA",
        "tree_heading_fg": "#111111",
        "tree_selected_bg": "#F0F0F0",
        "status_bg": "#FAFAFA",
        "status_fg": "#888888",
        "entry_bg": "#FFFFFF",
        "entry_fg": "#333333",
        "entry_select_bg": "#EEEEEE",
        "entry_select_fg": "#333333",
        "border_color": "#E0E0E0",
        "hover_bg": "#333333",
        "active_bg": "#000000",
        "calendar_bg": "#FFFFFF",
        "calendar_fg": "#333333",
        "calendar_header_bg": "#FAFAFA",
        "calendar_header_fg": "#111111",
        "calendar_select_bg": "#111111",
        "calendar_select_fg": "#FFFFFF",
        "calendar_weekend_bg": "#FAFAFA",
        "calendar_weekend_fg": "#888888",
    },
    # Soothing Dark - Soft charcoal, easier on eyes
    "Soothing Dark": {
        "bg": "#222222",
        "fg": "#E0E0E0",
        "header_bg": "#222222",
        "header_fg": "#FFFFFF",
        "button_bg": "#404040",
        "button_fg": "#FFFFFF",
        "tree_bg": "#2C2C2C",
        "tree_fg": "#E0E0E0",
        "tree_heading_bg": "#1A1A1A",
        "tree_heading_fg": "#E0E0E0",
        "tree_selected_bg": "#404040",
        "status_bg": "#222222",
        "status_fg": "#999999",
        "entry_bg": "#2C2C2C",
        "entry_fg": "#E0E0E0",
        "entry_select_bg": "#404040",
        "entry_select_fg": "#E0E0E0",
        "border_color": "#404040",
        "hover_bg": "#505050",
        "active_bg": "#606060",
        "calendar_bg": "#2C2C2C",
        "calendar_fg": "#E0E0E0",
        "calendar_header_bg": "#222222",
        "calendar_header_fg": "#E0E0E0",
        "calendar_select_bg": "#404040",
        "calendar_select_fg": "#FFFFFF",
        "calendar_weekend_bg": "#222222",
        "calendar_weekend_fg": "#999999",
    },
    # Matcha Latte - Soft pastel aesthetics
    "Matcha Latte": {
        "bg": "#FDFCF0",
        "fg": "#433E3F",
        "header_bg": "#FDFCF0",
        "header_fg": "#433E3F",
        "button_bg": "#A0C1B8",
        "button_fg": "#FFFFFF",
        "tree_bg": "#FFFFFF",
        "tree_fg": "#433E3F",
        "tree_heading_bg": "#FDFCF0",
        "tree_heading_fg": "#5C5455",
        "tree_selected_bg": "#E8F3F1",
        "status_bg": "#FDFCF0",
        "status_fg": "#8A8182",
        "entry_bg": "#FFFFFF",
        "entry_fg": "#433E3F",
        "entry_select_bg": "#E8F3F1",
        "entry_select_fg": "#433E3F",
        "border_color": "#D4EBE6",
        "hover_bg": "#8FB0A7",
        "active_bg": "#7E9F96",
        "calendar_bg": "#FFFFFF",
        "calendar_fg": "#433E3F",
        "calendar_header_bg": "#FDFCF0",
        "calendar_header_fg": "#5C5455",
        "calendar_select_bg": "#A0C1B8",
        "calendar_select_fg": "#FFFFFF",
        "calendar_weekend_bg": "#FAF9EB",
        "calendar_weekend_fg": "#8A8182",
    },
}
